# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kevin/ComputerVision

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kevin/ComputerVision

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevin/ComputerVision/CMakeFiles /home/kevin/ComputerVision/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevin/ComputerVision/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Main

# Build rule for target.
Main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Main
.PHONY : Main

# fast build rule for target.
Main/fast:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/build
.PHONY : Main/fast

#=============================================================================
# Target rules for targets named vlfeat_slic

# Build rule for target.
vlfeat_slic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vlfeat_slic
.PHONY : vlfeat_slic

# fast build rule for target.
vlfeat_slic/fast:
	$(MAKE) -f CMakeFiles/vlfeat_slic.dir/build.make CMakeFiles/vlfeat_slic.dir/build
.PHONY : vlfeat_slic/fast

Classifier/classifier.o: Classifier/classifier.cc.o
.PHONY : Classifier/classifier.o

# target to build an object file
Classifier/classifier.cc.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Classifier/classifier.cc.o
.PHONY : Classifier/classifier.cc.o

Classifier/classifier.i: Classifier/classifier.cc.i
.PHONY : Classifier/classifier.i

# target to preprocess a source file
Classifier/classifier.cc.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Classifier/classifier.cc.i
.PHONY : Classifier/classifier.cc.i

Classifier/classifier.s: Classifier/classifier.cc.s
.PHONY : Classifier/classifier.s

# target to generate assembly for a file
Classifier/classifier.cc.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Classifier/classifier.cc.s
.PHONY : Classifier/classifier.cc.s

Classifier/clipper.o: Classifier/clipper.cpp.o
.PHONY : Classifier/clipper.o

# target to build an object file
Classifier/clipper.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Classifier/clipper.cpp.o
.PHONY : Classifier/clipper.cpp.o

Classifier/clipper.i: Classifier/clipper.cpp.i
.PHONY : Classifier/clipper.i

# target to preprocess a source file
Classifier/clipper.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Classifier/clipper.cpp.i
.PHONY : Classifier/clipper.cpp.i

Classifier/clipper.s: Classifier/clipper.cpp.s
.PHONY : Classifier/clipper.s

# target to generate assembly for a file
Classifier/clipper.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Classifier/clipper.cpp.s
.PHONY : Classifier/clipper.cpp.s

Data/ImageObj.o: Data/ImageObj.cpp.o
.PHONY : Data/ImageObj.o

# target to build an object file
Data/ImageObj.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Data/ImageObj.cpp.o
.PHONY : Data/ImageObj.cpp.o

Data/ImageObj.i: Data/ImageObj.cpp.i
.PHONY : Data/ImageObj.i

# target to preprocess a source file
Data/ImageObj.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Data/ImageObj.cpp.i
.PHONY : Data/ImageObj.cpp.i

Data/ImageObj.s: Data/ImageObj.cpp.s
.PHONY : Data/ImageObj.s

# target to generate assembly for a file
Data/ImageObj.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Data/ImageObj.cpp.s
.PHONY : Data/ImageObj.cpp.s

Data/JSONImage.o: Data/JSONImage.cpp.o
.PHONY : Data/JSONImage.o

# target to build an object file
Data/JSONImage.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Data/JSONImage.cpp.o
.PHONY : Data/JSONImage.cpp.o

Data/JSONImage.i: Data/JSONImage.cpp.i
.PHONY : Data/JSONImage.i

# target to preprocess a source file
Data/JSONImage.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Data/JSONImage.cpp.i
.PHONY : Data/JSONImage.cpp.i

Data/JSONImage.s: Data/JSONImage.cpp.s
.PHONY : Data/JSONImage.s

# target to generate assembly for a file
Data/JSONImage.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Data/JSONImage.cpp.s
.PHONY : Data/JSONImage.cpp.s

Helper/FileManager.o: Helper/FileManager.cpp.o
.PHONY : Helper/FileManager.o

# target to build an object file
Helper/FileManager.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Helper/FileManager.cpp.o
.PHONY : Helper/FileManager.cpp.o

Helper/FileManager.i: Helper/FileManager.cpp.i
.PHONY : Helper/FileManager.i

# target to preprocess a source file
Helper/FileManager.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Helper/FileManager.cpp.i
.PHONY : Helper/FileManager.cpp.i

Helper/FileManager.s: Helper/FileManager.cpp.s
.PHONY : Helper/FileManager.s

# target to generate assembly for a file
Helper/FileManager.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Helper/FileManager.cpp.s
.PHONY : Helper/FileManager.cpp.s

LBP/histogram.o: LBP/histogram.cpp.o
.PHONY : LBP/histogram.o

# target to build an object file
LBP/histogram.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/LBP/histogram.cpp.o
.PHONY : LBP/histogram.cpp.o

LBP/histogram.i: LBP/histogram.cpp.i
.PHONY : LBP/histogram.i

# target to preprocess a source file
LBP/histogram.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/LBP/histogram.cpp.i
.PHONY : LBP/histogram.cpp.i

LBP/histogram.s: LBP/histogram.cpp.s
.PHONY : LBP/histogram.s

# target to generate assembly for a file
LBP/histogram.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/LBP/histogram.cpp.s
.PHONY : LBP/histogram.cpp.s

LBP/lbp.o: LBP/lbp.cpp.o
.PHONY : LBP/lbp.o

# target to build an object file
LBP/lbp.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/LBP/lbp.cpp.o
.PHONY : LBP/lbp.cpp.o

LBP/lbp.i: LBP/lbp.cpp.i
.PHONY : LBP/lbp.i

# target to preprocess a source file
LBP/lbp.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/LBP/lbp.cpp.i
.PHONY : LBP/lbp.cpp.i

LBP/lbp.s: LBP/lbp.cpp.s
.PHONY : LBP/lbp.s

# target to generate assembly for a file
LBP/lbp.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/LBP/lbp.cpp.s
.PHONY : LBP/lbp.cpp.s

LBP/lbpfeature.o: LBP/lbpfeature.cpp.o
.PHONY : LBP/lbpfeature.o

# target to build an object file
LBP/lbpfeature.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/LBP/lbpfeature.cpp.o
.PHONY : LBP/lbpfeature.cpp.o

LBP/lbpfeature.i: LBP/lbpfeature.cpp.i
.PHONY : LBP/lbpfeature.i

# target to preprocess a source file
LBP/lbpfeature.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/LBP/lbpfeature.cpp.i
.PHONY : LBP/lbpfeature.cpp.i

LBP/lbpfeature.s: LBP/lbpfeature.cpp.s
.PHONY : LBP/lbpfeature.s

# target to generate assembly for a file
LBP/lbpfeature.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/LBP/lbpfeature.cpp.s
.PHONY : LBP/lbpfeature.cpp.s

Main.o: Main.cpp.o
.PHONY : Main.o

# target to build an object file
Main.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Main.cpp.o
.PHONY : Main.cpp.o

Main.i: Main.cpp.i
.PHONY : Main.i

# target to preprocess a source file
Main.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Main.cpp.i
.PHONY : Main.cpp.i

Main.s: Main.cpp.s
.PHONY : Main.s

# target to generate assembly for a file
Main.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Main.cpp.s
.PHONY : Main.cpp.s

lib_vlfeat/vl/generic.o: lib_vlfeat/vl/generic.c.o
.PHONY : lib_vlfeat/vl/generic.o

# target to build an object file
lib_vlfeat/vl/generic.c.o:
	$(MAKE) -f CMakeFiles/vlfeat_slic.dir/build.make CMakeFiles/vlfeat_slic.dir/lib_vlfeat/vl/generic.c.o
.PHONY : lib_vlfeat/vl/generic.c.o

lib_vlfeat/vl/generic.i: lib_vlfeat/vl/generic.c.i
.PHONY : lib_vlfeat/vl/generic.i

# target to preprocess a source file
lib_vlfeat/vl/generic.c.i:
	$(MAKE) -f CMakeFiles/vlfeat_slic.dir/build.make CMakeFiles/vlfeat_slic.dir/lib_vlfeat/vl/generic.c.i
.PHONY : lib_vlfeat/vl/generic.c.i

lib_vlfeat/vl/generic.s: lib_vlfeat/vl/generic.c.s
.PHONY : lib_vlfeat/vl/generic.s

# target to generate assembly for a file
lib_vlfeat/vl/generic.c.s:
	$(MAKE) -f CMakeFiles/vlfeat_slic.dir/build.make CMakeFiles/vlfeat_slic.dir/lib_vlfeat/vl/generic.c.s
.PHONY : lib_vlfeat/vl/generic.c.s

lib_vlfeat/vl/host.o: lib_vlfeat/vl/host.c.o
.PHONY : lib_vlfeat/vl/host.o

# target to build an object file
lib_vlfeat/vl/host.c.o:
	$(MAKE) -f CMakeFiles/vlfeat_slic.dir/build.make CMakeFiles/vlfeat_slic.dir/lib_vlfeat/vl/host.c.o
.PHONY : lib_vlfeat/vl/host.c.o

lib_vlfeat/vl/host.i: lib_vlfeat/vl/host.c.i
.PHONY : lib_vlfeat/vl/host.i

# target to preprocess a source file
lib_vlfeat/vl/host.c.i:
	$(MAKE) -f CMakeFiles/vlfeat_slic.dir/build.make CMakeFiles/vlfeat_slic.dir/lib_vlfeat/vl/host.c.i
.PHONY : lib_vlfeat/vl/host.c.i

lib_vlfeat/vl/host.s: lib_vlfeat/vl/host.c.s
.PHONY : lib_vlfeat/vl/host.s

# target to generate assembly for a file
lib_vlfeat/vl/host.c.s:
	$(MAKE) -f CMakeFiles/vlfeat_slic.dir/build.make CMakeFiles/vlfeat_slic.dir/lib_vlfeat/vl/host.c.s
.PHONY : lib_vlfeat/vl/host.c.s

lib_vlfeat/vl/lbp.o: lib_vlfeat/vl/lbp.c.o
.PHONY : lib_vlfeat/vl/lbp.o

# target to build an object file
lib_vlfeat/vl/lbp.c.o:
	$(MAKE) -f CMakeFiles/vlfeat_slic.dir/build.make CMakeFiles/vlfeat_slic.dir/lib_vlfeat/vl/lbp.c.o
.PHONY : lib_vlfeat/vl/lbp.c.o

lib_vlfeat/vl/lbp.i: lib_vlfeat/vl/lbp.c.i
.PHONY : lib_vlfeat/vl/lbp.i

# target to preprocess a source file
lib_vlfeat/vl/lbp.c.i:
	$(MAKE) -f CMakeFiles/vlfeat_slic.dir/build.make CMakeFiles/vlfeat_slic.dir/lib_vlfeat/vl/lbp.c.i
.PHONY : lib_vlfeat/vl/lbp.c.i

lib_vlfeat/vl/lbp.s: lib_vlfeat/vl/lbp.c.s
.PHONY : lib_vlfeat/vl/lbp.s

# target to generate assembly for a file
lib_vlfeat/vl/lbp.c.s:
	$(MAKE) -f CMakeFiles/vlfeat_slic.dir/build.make CMakeFiles/vlfeat_slic.dir/lib_vlfeat/vl/lbp.c.s
.PHONY : lib_vlfeat/vl/lbp.c.s

lib_vlfeat/vl/random.o: lib_vlfeat/vl/random.c.o
.PHONY : lib_vlfeat/vl/random.o

# target to build an object file
lib_vlfeat/vl/random.c.o:
	$(MAKE) -f CMakeFiles/vlfeat_slic.dir/build.make CMakeFiles/vlfeat_slic.dir/lib_vlfeat/vl/random.c.o
.PHONY : lib_vlfeat/vl/random.c.o

lib_vlfeat/vl/random.i: lib_vlfeat/vl/random.c.i
.PHONY : lib_vlfeat/vl/random.i

# target to preprocess a source file
lib_vlfeat/vl/random.c.i:
	$(MAKE) -f CMakeFiles/vlfeat_slic.dir/build.make CMakeFiles/vlfeat_slic.dir/lib_vlfeat/vl/random.c.i
.PHONY : lib_vlfeat/vl/random.c.i

lib_vlfeat/vl/random.s: lib_vlfeat/vl/random.c.s
.PHONY : lib_vlfeat/vl/random.s

# target to generate assembly for a file
lib_vlfeat/vl/random.c.s:
	$(MAKE) -f CMakeFiles/vlfeat_slic.dir/build.make CMakeFiles/vlfeat_slic.dir/lib_vlfeat/vl/random.c.s
.PHONY : lib_vlfeat/vl/random.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Main"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vlfeat_slic"
	@echo "... Classifier/classifier.o"
	@echo "... Classifier/classifier.i"
	@echo "... Classifier/classifier.s"
	@echo "... Classifier/clipper.o"
	@echo "... Classifier/clipper.i"
	@echo "... Classifier/clipper.s"
	@echo "... Data/ImageObj.o"
	@echo "... Data/ImageObj.i"
	@echo "... Data/ImageObj.s"
	@echo "... Data/JSONImage.o"
	@echo "... Data/JSONImage.i"
	@echo "... Data/JSONImage.s"
	@echo "... Helper/FileManager.o"
	@echo "... Helper/FileManager.i"
	@echo "... Helper/FileManager.s"
	@echo "... LBP/histogram.o"
	@echo "... LBP/histogram.i"
	@echo "... LBP/histogram.s"
	@echo "... LBP/lbp.o"
	@echo "... LBP/lbp.i"
	@echo "... LBP/lbp.s"
	@echo "... LBP/lbpfeature.o"
	@echo "... LBP/lbpfeature.i"
	@echo "... LBP/lbpfeature.s"
	@echo "... Main.o"
	@echo "... Main.i"
	@echo "... Main.s"
	@echo "... lib_vlfeat/vl/generic.o"
	@echo "... lib_vlfeat/vl/generic.i"
	@echo "... lib_vlfeat/vl/generic.s"
	@echo "... lib_vlfeat/vl/host.o"
	@echo "... lib_vlfeat/vl/host.i"
	@echo "... lib_vlfeat/vl/host.s"
	@echo "... lib_vlfeat/vl/lbp.o"
	@echo "... lib_vlfeat/vl/lbp.i"
	@echo "... lib_vlfeat/vl/lbp.s"
	@echo "... lib_vlfeat/vl/random.o"
	@echo "... lib_vlfeat/vl/random.i"
	@echo "... lib_vlfeat/vl/random.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

